listen = "127.0.0.1:53"
upstream = ["1.1.1.1:53", "8.8.8.8:53"]
ttl_seconds = 30
log_level = "info"

[[record]]
domain = "jxck.io"
A = ["127.0.0.1"]
AAAA = ["::1"]

[[record]]
domain = "api.jxck.io"
A = ["127.0.0.2"]
AAAA = ["::1"]
